### ISSUE TITLE
Any chance this repo will be revived?

### ISSUE THREAD

**Issue by maphel** [c-frame/aframe-stereo-component#50]
Hi,
I'm interested in your project and would like to contribute. However, I've noticed there are at least 10 open pull requests that have been pending for a long time. Is there a chance someone will review them?

**Comment by oscarmarinmiro** [comment]
Hi, I'm sorry @maphel, due to some conflicts of interest I can no longer maintain the repo.

I'd be happy to do what @vincentfretin suggests, though. Do you want me to move the repo there or are you going to fork it in c-frame, @vincentfretin (no problem with either)

**Comment by oscarmarinmiro** [comment]
@vincentfretin just tried the transfer, but I'm getting this error

![Screenshot 2024-04-03 at 12 14 44](https://github.com/oscarmarinmiro/aframe-stereo-component/assets/886229/64d615a3-992f-4aa0-9b17-66ffa910792f)

**Comment by vincentfretin** [comment]
@oscarmarinmiro Your invitation to the c-frame organization expired a long time ago, I reinvited you. You should have received a mail, after you accept, you should be able to transfer the repo.

**Comment by vincentfretin** [comment]
Also if you can give me the permission to publish on npm that would be great.  My userid is also vincentfretin there.
https://www.npmjs.com/package/aframe-stereo-component

**Comment by oscarmarinmiro** [comment]
> @oscarmarinmiro Your invitation to the c-frame organization expired a long time ago, I reinvited you. You should have received a mail, after you accept, you should be able to transfer the repo.

@vincentfretin Done, repo transferred & I invited you as a maintainer on npm. Thanks for the patience and please let me know if you need anything more!

**Comment by vincentfretin** [comment]
Thank you @oscarmarinmiro all good!

**Comment by vincentfretin** [comment]
@maphel I merged all the relevant PR and updated the dist in master. If there is other changes you want to do, you can create a PR, I'll review it. I'll look at updating the build tools and make a new release later.
Latest build:
```html
<script src="https://cdn.jsdelivr.net/gh/c-frame/aframe-stereo-component@a3144d1/dist/aframe-stereo-component.min.js"></script>
```

**Comment by maphel** [comment]
Wow that went pretty fast in the right direction. I'm really happy to see a lot of progress here! 
Thanks for taking the time to clear things up @oscarmarinmiro!
I got some free time at the weekend for some coding.

Thanks guys!
